extends Node

signal prize_collected(prize: PrizeDefinition, owned_total: int)
signal play_consumed(pack_id: String, coins_remaining: int)
signal play_denied(pack_id: String, reason: String)
signal pack_prize_won(pack_id: String, prize: PrizeDefinition, prizes_earned: int, prizes_remaining: int)
signal machine_prize_won(machine_id: String, prize: PrizeDefinition, prizes_earned: int, prizes_remaining: int)
signal container_storage_changed(container: ContainerDefinition, stats: Dictionary)
signal crane_play_recorded(pack_id: String, total_plays: int)
signal user_data_changed()
signal user_data_loaded()
signal user_data_saved()
signal display_sticker_placed(placement: DisplayPlacement)
signal display_sticker_removed(instance_id: String)
signal display_sticker_moved(placement: DisplayPlacement)
signal display_room_changed(room: DisplayRoomInstance)
signal coins_changed(coins: int)
signal offline_income_applied(amount: int)
signal unopened_added(item: UnopenedItem)
signal unopened_revealed(item: UnopenedItem, container: ContainerDefinition, prize: PrizeDefinition)
signal pack_purchased(pack_id: String)
signal upgrade_purchased(upgrade_id: String)
signal collection_claimed(collection_id: String)
signal daily_quest_progress(quest_id: String, value: int)
signal daily_quest_claimed(quest_id: String)
signal prize_recycled(prize_id: String, amount: int)
signal claw_landing_indicator_changed(enabled: bool)
